using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace StateSmith.output
{
    ///// <summary>
    ///// Used to specify which events are allowed in the state machine.
    ///// Can be used on a method/field that returns a comma seperated string of event names, or an array of event names.
    ///// If not found in an RenderConfig, no event validation is done.
    ///// </summary>
    //[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property | AttributeTargets.Method, AllowMultiple = false)]
    //public class EventListAttribute : Attribute
    //{

    //}

    public interface IHasEventList
    {
        /// <summary>
        /// A comma seperated list of allowed event names. TODO case sensitive?
        /// </summary>
        public string EventList { get; }
    }

    public interface IRenderConfigC
    {
        /// <summary>
        /// Whatever this property returns will be placed at the top of the rendered .h file.
        /// </summary>
        public string HFileTop { get; }

        /// <summary>
        /// Whatever this property returns will be placed at the top of the rendered .c file.
        /// </summary>
        public string CFileTop { get; }

        string VariableDeclarations { get; }
    }

    public interface IRenderConfigJs
    {
        /// <summary>
        /// Whatever this property returns will be placed at the top of the rendered file.
        /// </summary>
        string FileTop { get; }

        string VariableDeclarations { get; }
    }

    public class DefaultRenderConfigJs : IRenderConfigJs
    {
        public virtual string FileTop => StringUtils.DeIndentTrim(@"
            // Autogenerated with StateSmith
        ");

        public virtual string VariableDeclarations => "";
    }

    public class DefaultRenderConfigC : IRenderConfigC
    {
        public virtual string HFileTop => StringUtils.DeIndentTrim(@"
            // Autogenerated with StateSmith
        ");

        public virtual string CFileTop => StringUtils.DeIndentTrim(@"
            // Autogenerated with StateSmith
        ");

        public virtual string VariableDeclarations => "";
    }
}
