//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar1.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGrammar1Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class Grammar1BaseListener : IGrammar1Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.optional_any_space"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptional_any_space([NotNull] Grammar1Parser.Optional_any_spaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.optional_any_space"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptional_any_space([NotNull] Grammar1Parser.Optional_any_spaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.ohs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOhs([NotNull] Grammar1Parser.OhsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.ohs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOhs([NotNull] Grammar1Parser.OhsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.state_defn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterState_defn([NotNull] Grammar1Parser.State_defnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.state_defn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitState_defn([NotNull] Grammar1Parser.State_defnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.state_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterState_name([NotNull] Grammar1Parser.State_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.state_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitState_name([NotNull] Grammar1Parser.State_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.nl_behaviors"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNl_behaviors([NotNull] Grammar1Parser.Nl_behaviorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.nl_behaviors"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNl_behaviors([NotNull] Grammar1Parser.Nl_behaviorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.nl_behavior"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNl_behavior([NotNull] Grammar1Parser.Nl_behaviorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.nl_behavior"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNl_behavior([NotNull] Grammar1Parser.Nl_behaviorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.behavior"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBehavior([NotNull] Grammar1Parser.BehaviorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.behavior"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBehavior([NotNull] Grammar1Parser.BehaviorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.order"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrder([NotNull] Grammar1Parser.OrderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.order"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrder([NotNull] Grammar1Parser.OrderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.triggers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriggers([NotNull] Grammar1Parser.TriggersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.triggers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriggers([NotNull] Grammar1Parser.TriggersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.trigger_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrigger_id([NotNull] Grammar1Parser.Trigger_idContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.trigger_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrigger_id([NotNull] Grammar1Parser.Trigger_idContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.trigger_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrigger_list([NotNull] Grammar1Parser.Trigger_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.trigger_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrigger_list([NotNull] Grammar1Parser.Trigger_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.guard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGuard([NotNull] Grammar1Parser.GuardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.guard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGuard([NotNull] Grammar1Parser.GuardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.guard_code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGuard_code([NotNull] Grammar1Parser.Guard_codeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.guard_code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGuard_code([NotNull] Grammar1Parser.Guard_codeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] Grammar1Parser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] Grammar1Parser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.oneline_action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneline_action([NotNull] Grammar1Parser.Oneline_actionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.oneline_action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneline_action([NotNull] Grammar1Parser.Oneline_actionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.member_access_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_access_operator([NotNull] Grammar1Parser.Member_access_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.member_access_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_access_operator([NotNull] Grammar1Parser.Member_access_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.member_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_access([NotNull] Grammar1Parser.Member_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.member_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_access([NotNull] Grammar1Parser.Member_accessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] Grammar1Parser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] Grammar1Parser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.group_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup_expression([NotNull] Grammar1Parser.Group_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.group_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup_expression([NotNull] Grammar1Parser.Group_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.square_brace_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSquare_brace_expression([NotNull] Grammar1Parser.Square_brace_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.square_brace_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSquare_brace_expression([NotNull] Grammar1Parser.Square_brace_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.braced_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBraced_expression([NotNull] Grammar1Parser.Braced_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.braced_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBraced_expression([NotNull] Grammar1Parser.Braced_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.line_comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine_comment([NotNull] Grammar1Parser.Line_commentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.line_comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine_comment([NotNull] Grammar1Parser.Line_commentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.star_comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStar_comment([NotNull] Grammar1Parser.Star_commentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.star_comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStar_comment([NotNull] Grammar1Parser.Star_commentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.function_args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_args([NotNull] Grammar1Parser.Function_argsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.function_args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_args([NotNull] Grammar1Parser.Function_argsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.function_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_arg([NotNull] Grammar1Parser.Function_argContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.function_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_arg([NotNull] Grammar1Parser.Function_argContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.simple_function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_function_call([NotNull] Grammar1Parser.Simple_function_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.simple_function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_function_call([NotNull] Grammar1Parser.Simple_function_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.any_code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAny_code([NotNull] Grammar1Parser.Any_codeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.any_code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAny_code([NotNull] Grammar1Parser.Any_codeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.code_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode_element([NotNull] Grammar1Parser.Code_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.code_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode_element([NotNull] Grammar1Parser.Code_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.code_line_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode_line_element([NotNull] Grammar1Parser.Code_line_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.code_line_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode_line_element([NotNull] Grammar1Parser.Code_line_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.code_line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode_line([NotNull] Grammar1Parser.Code_lineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.code_line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode_line([NotNull] Grammar1Parser.Code_lineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] Grammar1Parser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] Grammar1Parser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] Grammar1Parser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] Grammar1Parser.StringContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
