//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar1.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class Grammar1Lexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		LINE_ENDER=18, IDENTIFIER=19, LINE_COMMENT=20, STAR_COMMENT=21, STRING=22, 
		TICK_STRING=23, DIGIT=24, PERIOD=25, COMMA=26, CODE_SYMBOL=27, HWS=28;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"LINE_ENDER", "IDENTIFIER", "NOT_NL_CR", "LINE_COMMENT", "STAR_COMMENT", 
		"ESCAPED_CHAR", "NON_QUOTE_CHAR", "STRING_CHAR", "STRING", "TICK_STRING", 
		"IDENTIFIER_NON_DIGIT", "DIGIT", "PERIOD", "COMMA", "CODE_SYMBOL", "HWS"
	};


	public Grammar1Lexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public Grammar1Lexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'$STATEMACHINE'", "':'", "'$NOTES'", "'$ORTHO'", "'#'", "'('", 
		"')'", "'['", "']'", "'/'", "'::'", "'->'", "'{'", "'}'", "'-'", "'+'", 
		"'e'", null, null, null, null, null, null, null, "'.'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, "LINE_ENDER", "IDENTIFIER", "LINE_COMMENT", 
		"STAR_COMMENT", "STRING", "TICK_STRING", "DIGIT", "PERIOD", "COMMA", "CODE_SYMBOL", 
		"HWS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Grammar1.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static Grammar1Lexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1E', '\xCF', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x6', '\x13', '\x81', '\n', '\x13', '\r', '\x13', 
		'\xE', '\x13', '\x82', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\a', 
		'\x14', '\x88', '\n', '\x14', '\f', '\x14', '\xE', '\x14', '\x8B', '\v', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\a', '\x16', '\x93', '\n', '\x16', '\f', '\x16', 
		'\xE', '\x16', '\x96', '\v', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\a', '\x17', '\x9C', '\n', '\x17', '\f', '\x17', 
		'\xE', '\x17', '\x9F', '\v', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x5', '\x1A', '\xAB', '\n', '\x1A', 
		'\x3', '\x1B', '\x3', '\x1B', '\a', '\x1B', '\xAF', '\n', '\x1B', '\f', 
		'\x1B', '\xE', '\x1B', '\xB2', '\v', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1C', '\x3', '\x1C', '\a', '\x1C', '\xB8', '\n', '\x1C', '\f', 
		'\x1C', '\xE', '\x1C', '\xBB', '\v', '\x1C', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', '!', '\x3', '!', '\x5', 
		'!', '\xC9', '\n', '!', '\x3', '\"', '\x6', '\"', '\xCC', '\n', '\"', 
		'\r', '\"', '\xE', '\"', '\xCD', '\x3', '\x9D', '\x2', '#', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x2', '+', '\x16', '-', '\x17', 
		'/', '\x2', '\x31', '\x2', '\x33', '\x2', '\x35', '\x18', '\x37', '\x19', 
		'\x39', '\x2', ';', '\x1A', '=', '\x1B', '?', '\x1C', '\x41', '\x1D', 
		'\x43', '\x1E', '\x3', '\x2', '\t', '\x4', '\x2', '\f', '\f', '\xF', '\xF', 
		'\x3', '\x2', '$', '$', '\x3', '\x2', ')', ')', '\x6', '\x2', '&', '&', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', '\x32', ';', 
		'\v', '\x2', '#', '#', '\'', '(', ',', '-', '/', '/', '\x31', '\x31', 
		'<', '\x41', '`', '`', '~', '~', '\x80', '\x80', '\x4', '\x2', '\v', '\v', 
		'\"', '\"', '\x2', '\xD3', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '\x45', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'S', '\x3', '\x2', '\x2', '\x2', '\a', 'U', '\x3', '\x2', '\x2', '\x2', 
		'\t', '\\', '\x3', '\x2', '\x2', '\x2', '\v', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\r', '\x65', '\x3', '\x2', '\x2', '\x2', '\xF', 'g', '\x3', '\x2', 
		'\x2', '\x2', '\x11', 'i', '\x3', '\x2', '\x2', '\x2', '\x13', 'k', '\x3', 
		'\x2', '\x2', '\x2', '\x15', 'm', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'o', '\x3', '\x2', '\x2', '\x2', '\x19', 'r', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', 'u', '\x3', '\x2', '\x2', '\x2', '\x1D', 'w', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', 'y', '\x3', '\x2', '\x2', '\x2', '!', '{', '\x3', '\x2', 
		'\x2', '\x2', '#', '}', '\x3', '\x2', '\x2', '\x2', '%', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\'', '\x84', '\x3', '\x2', '\x2', '\x2', ')', '\x8C', 
		'\x3', '\x2', '\x2', '\x2', '+', '\x8E', '\x3', '\x2', '\x2', '\x2', '-', 
		'\x97', '\x3', '\x2', '\x2', '\x2', '/', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\xA6', '\x3', '\x2', '\x2', '\x2', '\x33', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\xAC', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\x39', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', ';', '\xC0', '\x3', '\x2', '\x2', '\x2', '=', '\xC2', '\x3', '\x2', 
		'\x2', '\x2', '?', '\xC4', '\x3', '\x2', '\x2', '\x2', '\x41', '\xC8', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\xCB', '\x3', '\x2', '\x2', '\x2', 
		'\x45', '\x46', '\a', '&', '\x2', '\x2', '\x46', 'G', '\a', 'U', '\x2', 
		'\x2', 'G', 'H', '\a', 'V', '\x2', '\x2', 'H', 'I', '\a', '\x43', '\x2', 
		'\x2', 'I', 'J', '\a', 'V', '\x2', '\x2', 'J', 'K', '\a', 'G', '\x2', 
		'\x2', 'K', 'L', '\a', 'O', '\x2', '\x2', 'L', 'M', '\a', '\x43', '\x2', 
		'\x2', 'M', 'N', '\a', '\x45', '\x2', '\x2', 'N', 'O', '\a', 'J', '\x2', 
		'\x2', 'O', 'P', '\a', 'K', '\x2', '\x2', 'P', 'Q', '\a', 'P', '\x2', 
		'\x2', 'Q', 'R', '\a', 'G', '\x2', '\x2', 'R', '\x4', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\a', '<', '\x2', '\x2', 'T', '\x6', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\a', '&', '\x2', '\x2', 'V', 'W', '\a', 'P', '\x2', 
		'\x2', 'W', 'X', '\a', 'Q', '\x2', '\x2', 'X', 'Y', '\a', 'V', '\x2', 
		'\x2', 'Y', 'Z', '\a', 'G', '\x2', '\x2', 'Z', '[', '\a', 'U', '\x2', 
		'\x2', '[', '\b', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\a', '&', '\x2', 
		'\x2', ']', '^', '\a', 'Q', '\x2', '\x2', '^', '_', '\a', 'T', '\x2', 
		'\x2', '_', '`', '\a', 'V', '\x2', '\x2', '`', '\x61', '\a', 'J', '\x2', 
		'\x2', '\x61', '\x62', '\a', 'Q', '\x2', '\x2', '\x62', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x63', '\x64', '\a', '%', '\x2', '\x2', '\x64', '\f', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x66', '\a', '*', '\x2', '\x2', '\x66', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '+', '\x2', '\x2', 
		'h', '\x10', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', ']', '\x2', '\x2', 
		'j', '\x12', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', '_', '\x2', '\x2', 
		'l', '\x14', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\a', '\x31', '\x2', 
		'\x2', 'n', '\x16', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\a', '<', '\x2', 
		'\x2', 'p', 'q', '\a', '<', '\x2', '\x2', 'q', '\x18', '\x3', '\x2', '\x2', 
		'\x2', 'r', 's', '\a', '/', '\x2', '\x2', 's', 't', '\a', '@', '\x2', 
		'\x2', 't', '\x1A', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', '}', '\x2', 
		'\x2', 'v', '\x1C', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', '\x7F', 
		'\x2', '\x2', 'x', '\x1E', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', 
		'/', '\x2', '\x2', 'z', ' ', '\x3', '\x2', '\x2', '\x2', '{', '|', '\a', 
		'-', '\x2', '\x2', '|', '\"', '\x3', '\x2', '\x2', '\x2', '}', '~', '\a', 
		'g', '\x2', '\x2', '~', '$', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x81', 
		'\t', '\x2', '\x2', '\x2', '\x80', '\x7F', '\x3', '\x2', '\x2', '\x2', 
		'\x81', '\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '&', 
		'\x3', '\x2', '\x2', '\x2', '\x84', '\x89', '\x5', '\x39', '\x1D', '\x2', 
		'\x85', '\x88', '\x5', '\x39', '\x1D', '\x2', '\x86', '\x88', '\x5', ';', 
		'\x1E', '\x2', '\x87', '\x85', '\x3', '\x2', '\x2', '\x2', '\x87', '\x86', 
		'\x3', '\x2', '\x2', '\x2', '\x88', '\x8B', '\x3', '\x2', '\x2', '\x2', 
		'\x89', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', 
		'\x2', '\x2', '\x8A', '(', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x89', 
		'\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\n', '\x2', '\x2', '\x2', 
		'\x8D', '*', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', '\x31', 
		'\x2', '\x2', '\x8F', '\x90', '\a', '\x31', '\x2', '\x2', '\x90', '\x94', 
		'\x3', '\x2', '\x2', '\x2', '\x91', '\x93', '\x5', ')', '\x15', '\x2', 
		'\x92', '\x91', '\x3', '\x2', '\x2', '\x2', '\x93', '\x96', '\x3', '\x2', 
		'\x2', '\x2', '\x94', '\x92', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', 
		'\x3', '\x2', '\x2', '\x2', '\x95', ',', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x94', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\a', '\x31', '\x2', 
		'\x2', '\x98', '\x99', '\a', ',', '\x2', '\x2', '\x99', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x9C', '\v', '\x2', '\x2', '\x2', '\x9B', 
		'\x9A', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', ',', '\x2', 
		'\x2', '\xA1', '\xA2', '\a', '\x31', '\x2', '\x2', '\xA2', '.', '\x3', 
		'\x2', '\x2', '\x2', '\xA3', '\xA4', '\a', '^', '\x2', '\x2', '\xA4', 
		'\xA5', '\v', '\x2', '\x2', '\x2', '\xA5', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\xA7', '\n', '\x3', '\x2', '\x2', '\xA7', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\xA8', '\xAB', '\x5', '/', '\x18', '\x2', '\xA9', 
		'\xAB', '\x5', '\x31', '\x19', '\x2', '\xAA', '\xA8', '\x3', '\x2', '\x2', 
		'\x2', '\xAA', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAB', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xB0', '\a', '$', '\x2', '\x2', '\xAD', 
		'\xAF', '\x5', '\x33', '\x1A', '\x2', '\xAE', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xAE', '\x3', 
		'\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB1', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xB4', '\a', '$', '\x2', '\x2', '\xB4', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\xB5', '\xB9', '\t', '\x4', '\x2', '\x2', '\xB6', 
		'\xB8', '\x5', '\x33', '\x1A', '\x2', '\xB7', '\xB6', '\x3', '\x2', '\x2', 
		'\x2', '\xB8', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xB9', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBA', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB9', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\xBD', '\t', '\x4', '\x2', '\x2', '\xBD', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\xBE', '\xBF', '\t', '\x5', '\x2', '\x2', '\xBF', 
		':', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\t', '\x6', '\x2', '\x2', 
		'\xC1', '<', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC3', '\a', '\x30', 
		'\x2', '\x2', '\xC3', '>', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', 
		'\a', '.', '\x2', '\x2', '\xC5', '@', '\x3', '\x2', '\x2', '\x2', '\xC6', 
		'\xC9', '\t', '\a', '\x2', '\x2', '\xC7', '\xC9', '\x5', '=', '\x1F', 
		'\x2', '\xC8', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '\xC9', '\x42', '\x3', '\x2', '\x2', '\x2', '\xCA', 
		'\xCC', '\t', '\b', '\x2', '\x2', '\xCB', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\xCC', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xCE', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\r', '\x2', '\x82', '\x87', '\x89', 
		'\x94', '\x9D', '\xAA', '\xB0', '\xB9', '\xC8', '\xCD', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
