//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar1.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGrammar1Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class Grammar1BaseListener : IGrammar1Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.state_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterState_name([NotNull] Grammar1Parser.State_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.state_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitState_name([NotNull] Grammar1Parser.State_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.trigger_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrigger_list([NotNull] Grammar1Parser.Trigger_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.trigger_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrigger_list([NotNull] Grammar1Parser.Trigger_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.triggers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriggers([NotNull] Grammar1Parser.TriggersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.triggers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriggers([NotNull] Grammar1Parser.TriggersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.guard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGuard([NotNull] Grammar1Parser.GuardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.guard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGuard([NotNull] Grammar1Parser.GuardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] Grammar1Parser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] Grammar1Parser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.braced_action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBraced_action([NotNull] Grammar1Parser.Braced_actionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.braced_action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBraced_action([NotNull] Grammar1Parser.Braced_actionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.naked_action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNaked_action([NotNull] Grammar1Parser.Naked_actionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.naked_action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNaked_action([NotNull] Grammar1Parser.Naked_actionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.behavior"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBehavior([NotNull] Grammar1Parser.BehaviorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.behavior"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBehavior([NotNull] Grammar1Parser.BehaviorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] Grammar1Parser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] Grammar1Parser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.group_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup_expression([NotNull] Grammar1Parser.Group_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.group_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup_expression([NotNull] Grammar1Parser.Group_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.square_brace_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSquare_brace_expression([NotNull] Grammar1Parser.Square_brace_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.square_brace_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSquare_brace_expression([NotNull] Grammar1Parser.Square_brace_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.braced_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBraced_expression([NotNull] Grammar1Parser.Braced_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.braced_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBraced_expression([NotNull] Grammar1Parser.Braced_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Grammar1Parser.code_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode_expression([NotNull] Grammar1Parser.Code_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Grammar1Parser.code_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode_expression([NotNull] Grammar1Parser.Code_expressionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
