using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace StateSmith.output.UserConfig
{
    public interface IRenderConfigC
    {
        /// <summary>
        /// Whatever this property returns will be placed at the top of the rendered .h file.
        /// </summary>
        string HFileTop => StringUtils.DeIndentTrim(@"
            // Autogenerated with StateSmith
        ");

        /// <summary>
        /// Whatever this property returns will be placed at the top of the rendered .c file.
        /// </summary>
        string CFileTop => StringUtils.DeIndentTrim(@"
            // Autogenerated with StateSmith
        ");

        string VariableDeclarations => "";
    }
}
